name: touch_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:

  advance_notification: ^1.0.6
  animate_do: ^3.0.2
  awesome_snackbar_content: ^0.1.3
  equatable: ^2.0.5
  


  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  google_nav_bar: ^5.0.6
  hexcolor: ^3.0.1
  http: ^0.13.6
  image_picker: ^0.8.7+5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
