name: touch_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  advance_notification: ^1.0.6
  animate_do: ^3.0.2
  awesome_select: ^6.0.0
  awesome_snackbar_content: ^0.1.3
  chips_choice_null_safety: ^2.0.3
  equatable: ^2.0.5
  favorite_button: ^0.0.4
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_multi_select_items: ^0.4.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  hexcolor: ^3.0.1
  multi_select_flutter: ^4.1.3
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
