// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQG0SwXdEaNAegasnjJdXVSjDgi8-43Y',
    appId: '1:1015375405539:web:e41b173c81bedc87c300d6',
    messagingSenderId: '1015375405539',
    projectId: 'touch-69bee',
    authDomain: 'touch-69bee.firebaseapp.com',
    storageBucket: 'touch-69bee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSeDd0XFReY9ZMcQjkNEgBFDdiK8uwFUI',
    appId: '1:1015375405539:android:534a6da53cf26788c300d6',
    messagingSenderId: '1015375405539',
    projectId: 'touch-69bee',
    storageBucket: 'touch-69bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC56bIMF7Fz41YlDTU_NQ4x_6hSGITZvW4',
    appId: '1:1015375405539:ios:007219073316c1fac300d6',
    messagingSenderId: '1015375405539',
    projectId: 'touch-69bee',
    storageBucket: 'touch-69bee.appspot.com',
    iosClientId: '1015375405539-unbutpqiagse3va3lmq2cj22k8gs3f9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.touchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC56bIMF7Fz41YlDTU_NQ4x_6hSGITZvW4',
    appId: '1:1015375405539:ios:007219073316c1fac300d6',
    messagingSenderId: '1015375405539',
    projectId: 'touch-69bee',
    storageBucket: 'touch-69bee.appspot.com',
    iosClientId: '1015375405539-unbutpqiagse3va3lmq2cj22k8gs3f9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.touchApp',
  );
}
